### ISSUE TITLE
Plugin will not install in QGIS 3.26

### ISSUE THREAD

**Issue by zeddock** [JMG30/flight_planner#15] opened 2022-08-25 16:40 UTC
I have installed several plugins without issue, but this one fails and states:
=====
```
Couldn't load plugin 'flight_planner' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'scipy' 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/__init__.py", line 35, in classFactory
    from .flight_planner import FlightPlanner
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/flight_planner.py", line 31, in 
    from .flight_planner_dialog import FlightPlannerDialog
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/flight_planner_dialog.py", line 41, in 
    from .worker import Worker
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/flight_planner/worker.py", line 11, in 
    import scipy.ndimage as ndimage
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'scipy'


Python version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0] 
QGIS version: 3.26.1-Buenos Aires Buenos Aires, exported 

Python Path:
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgissprp/sprp
/usr/share/qgis/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python3.10/site-packages
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qLidar/libCpp
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qLidar
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qLidar/libCpp
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qLidar
/home/jim/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs
```

=====

**Comment by JMG30** [comment] 2022-08-28 17:33
Closed as a duplicate of https://github.com/JMG30/flight_planner/issues/10

**Closed as completed by JMG30** 2022-08-28 17:33 UTC
